# Generated by Django 4.2.5 on 2024-09-03 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import review.utils.status


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type_result', models.CharField(max_length=255)),
                ('marbling_level', models.CharField(max_length=55)),
                ('fat_distribution', models.CharField(max_length=55)),
                ('result', models.TextField()),
                ('status', models.CharField(choices=[('aguardando análise', 'WAITING'), ('em análise', 'PROCESSING'), ('concluído', 'COMPLETED')], default=review.utils.status.CustomerStatus['WAITING'], max_length=30)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='animal.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.animal')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResultHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('previous_status', models.CharField(choices=[('aguardando análise', 'WAITING'), ('em análise', 'PROCESSING'), ('concluído', 'COMPLETED')], default=review.utils.status.CustomerStatus['PROCESSING'], max_length=20)),
                ('new_status', models.CharField(choices=[('aguardando análise', 'WAITING'), ('em análise', 'PROCESSING'), ('concluído', 'COMPLETED')], default=review.utils.status.CustomerStatus['PROCESSING'], max_length=20)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.analysisresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
