# Generated by Django 4.2.5 on 2024-05-28 22:59

from django.db import migrations, models
import review.utils.status


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='status',
            field=models.CharField(choices=[('aguardando análise', 'WAITING'), ('em análise', 'PROCESSING'), ('concluído', 'COMPLETED')], default=review.utils.status.CustomerStatus['WAITING'], max_length=30),
        ),
    ]
