# Generated by Django 4.2.5 on 2024-09-15 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='animal',
            new_name='animal_id',
        ),
    ]
