# Generated by Django 4.2.5 on 2024-04-19 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='animal',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='animal.animal'),
            preserve_default=False,
        ),
    ]
