# Generated by Django 4.2.5 on 2024-04-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
        ('review', '0002_uploadedfile_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animal.animal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisresulthistory',
            name='analysis_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='review.analysisresult'),
            preserve_default=False,
        ),
    ]
