# Generated by Django 4.2.5 on 2024-09-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_animal_uploadedfile_animal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='fat_distribution',
            field=models.CharField(default='Em análise', max_length=75),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='marbling_level',
            field=models.CharField(default='Em análise', max_length=75),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='result',
            field=models.TextField(default=''),
        ),
    ]
