# Generated by Django 4.2.5 on 2024-06-07 03:08

from django.db import migrations, models
import review.utils.status


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_analysisresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresulthistory',
            name='new_status',
            field=models.CharField(choices=[('aguardando análise', 'WAITING'), ('em análise', 'PROCESSING'), ('concluído', 'COMPLETED')], default=review.utils.status.CustomerStatus['PROCESSING'], max_length=20),
        ),
        migrations.AlterField(
            model_name='analysisresulthistory',
            name='previous_status',
            field=models.CharField(choices=[('aguardando análise', 'WAITING'), ('em análise', 'PROCESSING'), ('concluído', 'COMPLETED')], default=review.utils.status.CustomerStatus['PROCESSING'], max_length=20),
        ),
    ]
