# Generated by Django 4.2.5 on 2024-06-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_alter_animal_animal_conditions_alter_animal_gender'),
        ('review', '0003_alter_analysisresulthistory_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='animal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='animal.animal'),
        ),
    ]
