# Generated by Django 4.2.5 on 2023-10-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
