# Generated by Django 4.2.5 on 2024-03-25 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('identifier', models.CharField(max_length=5)),
                ('animal_conditions', models.CharField(choices=[('apt_for_slaughter', 'Apto para o abate'), ('sick_or_injured', 'Doente ou machucado'), ('wrong_batch', 'Animal está no lote errado')], max_length=20)),
                ('animal_species', models.CharField(choices=[('bovine', 'Bovino'), ('caprine', 'Caprino'), ('ovine', 'Ovino'), ('porcine', 'Suíno')], max_length=8)),
                ('breed', models.CharField(default='', max_length=255)),
                ('productive_situation', models.CharField(max_length=255)),
                ('animal_age', models.IntegerField(default=0)),
                ('data_joined', models.DateField()),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
