# Generated by Django 4.2.5 on 2024-03-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
