# Generated by Django 4.2.5 on 2024-09-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='reprodutiveSituation',
            new_name='reproductiveSituation',
        ),
    ]
