# Generated by Django 4.2.5 on 2024-03-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_alter_animal_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='data_joined',
        ),
    ]
