# Generated by Django 4.2.5 on 2024-09-03 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_rename_reprodutivesituation_animal_reproductivesituation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='teeth',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(44)]),
        ),
    ]
