# Generated by Django 4.2.5 on 2024-06-07 03:08

import animal.utils.animal_conditions
import animal.utils.genders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_conditions',
            field=models.CharField(choices=[('Apto para o abate', 'APT_FOR_SLAUGHTER'), ('Doente ou machucado', 'SICK_OR_INJURED'), ('Animal está no lote errado', 'WRONG_BATCH')], default=animal.utils.animal_conditions.CustomerConditions['APT_FOR_SLAUGHTER'], max_length=26),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('macho', 'MALE'), ('femêa', 'FEMALE')], default=animal.utils.genders.CustomerGender['MALE'], max_length=8),
        ),
    ]
