# Generated by Django 4.2.5 on 2024-04-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
    ]
