# Generated by Django 4.2.5 on 2024-03-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_remove_animal_data_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='animal',
            name='productive_situation',
            field=models.CharField(max_length=125),
        ),
    ]
