# Generated by Django 4.2.5 on 2024-11-19 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_alter_animal_teeth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2400)], verbose_name='animal age'),
        ),
    ]
