# Generated by Django 4.2.5 on 2024-03-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_animal_description_alter_animal_breed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='time',
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_age',
            field=models.IntegerField(default=0, verbose_name='animal age'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='productive_situation',
            field=models.CharField(max_length=125, verbose_name='productive situation'),
        ),
    ]
