# Generated by Django 4.2.5 on 2024-03-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_remove_animal_time_alter_animal_animal_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_age',
            field=models.IntegerField(verbose_name='animal age'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_species',
            field=models.CharField(choices=[('bovine', 'Bovino'), ('caprine', 'Caprino'), ('ovine', 'Ovino'), ('porcine', 'Suíno')], max_length=8, verbose_name='animal species'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(max_length=125),
        ),
    ]
