# Generated by Django 4.2.5 on 2024-04-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_alter_animal_animal_age_alter_animal_animal_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='identifier',
            field=models.CharField(default='4VHSY', max_length=5),
        ),
    ]
