# Generated by Django 4.2.5 on 2024-04-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0007_alter_animal_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='identifier',
            field=models.CharField(default='R7VDG', max_length=5),
        ),
    ]
